import re

#source: https://en.wiktionary.org/wiki/Category:English_abbreviations

ABBREVIATIONS_COMMON = [(re.compile(r'\b%s\.?(,?)\b' % x[0]), r'%s\1 ' % x[1]) for x in [
		("abbr", "abbreviation"),
		("abbrev", "abbreviation"),
		#("abr", "abridged"),
		("abstr", "abstract"),
		("AI", "artificial intelligence"),
		#("Amer", "american"),
		#("am", "ante meridiem"),
		#("AM", "ante meridiem"),
		("approx", "approximately"),
		("[Aa]pr", "april"),
		("[Aa]pt", "apartment"),
		("[Aa]pts", "apartments"),
		("appt", "appointment"),
		("[Aa]ssoc", "association"),
		("[Aa]sst", "assistant"),
		#("[Aa]ug", "august"),
		#("auth", "authority"),
		("[Aa]v", "avenue"),
		("ave", "average"),
		("[Bb]lvd", "boulevard"),
		("ca", "circa"),
		("Capt", "captain"),
		("cert", "certified"),
		("cllr", "councillor"),
		("co", "company"),
		("c\/o", "care of"),
		("\.com", " dot com"),
		("colloq", "colloquial"),
		("Comdr", "commander"),
		("cont\'d", "continued"),
		("Corp", "corporation"),
		("Ctrl", "control"),
		("Dr", "doctor"),
		("dr", "drive"),
		#("[Dd]ec", "december"),
		("[Dd]ept", "department"),
		("[Dd]istrib", "distributor"),
		("[Ee]d", "edition"),
		("est", "established"),
		("etc", "etcetra"),
		("[Ee]xec", "executive"),
		#("[Ff]eb", "february"),
		("[Ff]wd", "forward"),
		("[Gg]ov", "government"),
		("[Gg]ov\'t", "government"),
		("GMT", "greenwich mean time"),
		("Hebr", "hebrew"),
		("[Hh]on\'ble", "honorable"),
		("Hon", "honorable"),
		("i\.e", "that is"),
		("illust?", "illustration"),
		("[Ii]ntro", "introduction"),
		("[Ii]nc", "incorporated"),
		#("[Jj]an", "january"),
		("[Jj]our", "journal"),
		("Jr", "junior"),
		("[Ll]n", "lane"),
		("Lieut", "lieutenant"),
		("[Ll]td", "limited"),
		("Maj", "major"),
		("mfg", "manufacturing"),
		("[Mm]gmt", "management"),
		("min", "minute"),
		("misc", "miscellaneous"),
		("mktg", "marketing"),
		("Mr", "mister"),
		("Mrs", "missus"),
		("Ms", "miss"),
		("Mme", "madame"),
		("n\.b", "nota bene"),
		("net wt", "net weight"),
		#("[Nn]ov", "november"),
		#("no", "number"),
		#("occupn", "occupation"),
		#("[Oo]ct", "october"),
		("[Oo]rg", "organisation"),
		("PM", "prime minister"), #conflict with pm in time expressions
		#("pm", "post meridiem"),
		#("PM", "post meridiem"),
		("[Pp]res", "president"),
		("Prof", "professor"),
		("[Pp]vt", "private"),
		("[Qq]uot", "quotation"),
		("[Rr]egd", "registered"),
		("[Rr]egds", "regards"),
		#("sched", "schedule"),
		("sec", "section"),
		#("[Ss]ept", "september"),
		("smth", "something"),
		("Sqn Ldr", "squadron leader"),
		("Sr", "senior"),
		("St", "saint"),
		("st", "street"),
		("tbsp", "tablespoon"),
		("[Tt]el", "telephone"),
		("tsp", "teaspoon"),
		("UK", "United Kingdom"),
		("unabr", "unabridged"),
		("unk", "unknown"),
		("US", "United States"),
		("vol", "volume"),
		("vols", "volumes"),
		("[Vv]s", "versus"),
		#("viz", "namely"),
		("wt", "weight"),
		("WWI", "world war one"),
		("WWII", "world war two"),
		("WWIII", "world war three"),
		("WW1", "world war one"),
		("WW2", "world war two"),
		("WW3", "world war three"),
		("[Xx]mas", "christmas"),
		#("N", "North"),
		#("E", "East"),
		#("W", "West"),
		#("S", "South"),
		("@", " at"),
		("#", "hashtag"),
		("&", " and"),
		("\+", " plus"),
		("\=", " is equal to"),
		("\*", " times"),
]]


class AbbreviationConverter:
	def __init__(self,lang):
		super(AbbreviationConverter,self).__init__()
		self.lang = lang

	def transform(self,text):
		text = self.convert_abbreviations(text)
		return text

	def convert_abbreviations(self,text):
		for regex, replacement in ABBREVIATIONS_COMMON:
			try:
				text = re.sub(regex, replacement, text)
			except:
				print('Abbreviation conversion failed')

		return text
